package com.officemind.domain.notification;

import com.officemind.domain.shared.AggregateRoot;
import com.officemind.domain.shared.EntityId;

import java.time.Instant;
import java.util.Objects;

/**
 * A user-facing notification generated by system events such as
 * document indexing completing or failing (Phase 11).
 */
public class Notification extends AggregateRoot {

    private final EntityId id;
    private final String userId;
    private final NotificationType type;
    private final String title;
    private final String body;
    private boolean read;
    private final Instant createdAt;

    private Notification(EntityId id, String userId, NotificationType type,
                         String title, String body, boolean read, Instant createdAt) {
        this.id = Objects.requireNonNull(id);
        this.userId = Objects.requireNonNull(userId);
        this.type = Objects.requireNonNull(type);
        this.title = Objects.requireNonNull(title);
        this.body = body;
        this.read = read;
        this.createdAt = createdAt;
    }

    public static Notification create(String userId, NotificationType type, String title, String body) {
        return new Notification(EntityId.generate(), userId, type, title, body, false, Instant.now());
    }

    public static Notification rehydrate(EntityId id, String userId, NotificationType type,
                                          String title, String body, boolean read, Instant createdAt) {
        return new Notification(id, userId, type, title, body, read, createdAt);
    }

    public void markRead() { this.read = true; }

    public EntityId getId() { return id; }
    public String getUserId() { return userId; }
    public NotificationType getType() { return type; }
    public String getTitle() { return title; }
    public String getBody() { return body; }
    public boolean isRead() { return read; }
    public Instant getCreatedAt() { return createdAt; }
}
